### PR TITLE
Adding secondaryAxis support

### PR DESCRIPTION
**Pull request by AgarFu**

### CODE REVIEW

**Review by louism517 — CHANGES_REQUESTED** [review]
Thanks for the PR. Looks good. 

Could you just add the field into `fixtures/paginated-dashboard-0.json` so it gets some sort of test coverage?

**Comment by AgarFu** [comment]
Thx, as soon as you release a new version with this change I'll send a PR against the terraform provider to support the secondaryAxis flag as well.

**Comment by AgarFu** [comment]
@louism517 is there any other change that you want me to do?

**Comment by louism517** [comment]
@AgarFu Apologies for the delay. This looks good, happy to merge.

**Pull request merged**
